version: '3.8'

services:
  nginx:
    image: 172.16.242.4:15000/san-exporter-netapp-nginx:0.1.0
    build: ./nginx

  web:
    image: 172.16.242.4:15000/san-exporter-netapp-web:0.1.0
    build:
      context: .
      dockerfile: Dockerfile.prod