{
 "title": "SAN Storage",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "backend", "label": "Storage", "query": "netapp" },
   {
    "name": "pool",
    "label": "Pool",
    "query": {
     "query": "label_values(san_pool_total_capacity_mib{backend_name=~\"$backend\"},pool_name)"
    }
   },
   {
    "name": "node",
    "label": "Controller node",
    "query": {
     "query": "label_values(san_cpu_total{backend_name=~\"$backend\",cpu=~\"0\",mode=~\"idlePct\"},node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total LUN records (total volumes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "repeat": "pool",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "total_lun{backend_name=\"netapp\",cluster_name=\"FAS8300-PV01\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\"}-1"
    }
   ]
  },
  {
   "title": "Total controllers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(san_node_state{backend_name=~\"$backend\"})"
    }
   ]
  },
  {
   "title": "Total SSD capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_totalCapacityMiB{backend_name=~\"$backend\"}"
    }
   ]
  },
  {
   "title": "SSD used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_allocatedCapacityMiB{backend_name=~\"$backend\"}"
    }
   ]
  },
  {
   "title": "SSD free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_freeCapacityMiB{backend_name=~\"$backend\"}"
    }
   ]
  },
  {
   "title": "CPU - Node Controller PV 01 - 01",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "san_cpu_total_01{backend_name=~\"$backend\"}"
    }
   ]
  },
  {
   "title": "Cluster controllers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(san_node_state{backend_name=~\"$backend\"})"
    }
   ]
  },
  {
   "title": "Online controllers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(san_node_state{backend_name=~\"$backend\"} == 1)"
    }
   ]
  },
  {
   "title": "Total HDD capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 4 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hdd_totalCapacityMiB{backend_name=\"netapp\",cluster_name=\"FAS8300-PV01\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\"}"
    }
   ]
  },
  {
   "title": "HDD used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 4 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hdd_allocatedCapacityMiB{backend_name=\"netapp\",cluster_name=\"FAS8300-PV01\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\"}"
    }
   ]
  },
  {
   "title": "HDD free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 4 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "hdd_totalCapacityMiB{backend_name=\"netapp\",cluster_name=\"FAS8300-PV01\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\"}"
    }
   ]
  },
  {
   "title": "Graph CPU - Node Controller PV 01 - 01",
   "type": "graph",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 7 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "san_cpu_total_01{backend_name=~\"$backend\"}",
     "legendFormat": "{{cluster_name}}-01"
    }
   ]
  },
  {
   "title": "Graph CPU - Node Controller PV 01 - 02",
   "type": "graph",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 9, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "san_cpu_total_02{backend_name=~\"$backend\"}",
     "legendFormat": "{{cluster_name}}-02"
    }
   ]
  },
  {
   "title": "CPU - Node Controller PV 01 - 02",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "san_cpu_total_02{backend_name=~\"$backend\"}"
    }
   ]
  },
  { "title": "Pools capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "FAS8300-SSD-1 (CINDER_GOLD_01)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "san_pool_total_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_GOLD_01\"}",
     "legendFormat": "total"
    },
    {
     "expr": "san_pool_used_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_GOLD_01\"}",
     "legendFormat": "used"
    },
    {
     "expr": "san_pool_free_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_GOLD_01\"}",
     "legendFormat": "free"
    },
    { "expr": "san_storage_info", "legendFormat": "ssd1" }
   ]
  },
  {
   "title": "FAS8300-SSD-2 (CINDER_GOLD_02)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "san_pool_total_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_GOLD_02\"}",
     "legendFormat": "total"
    },
    {
     "expr": "san_pool_used_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_GOLD_02\"}",
     "legendFormat": "used"
    },
    {
     "expr": "san_pool_free_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_GOLD_02\"}",
     "legendFormat": "free"
    },
    { "expr": "san_storage_info", "legendFormat": "ssd2" }
   ]
  },
  {
   "title": "FAS8300-HDD-1 (CINDER_BRONZE_01)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "san_pool_total_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_BRONZE_01\"}",
     "legendFormat": "total"
    },
    {
     "expr": "san_pool_used_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_BRONZE_01\"}",
     "legendFormat": "used"
    },
    {
     "expr": "san_pool_free_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_BRONZE_01\"}",
     "legendFormat": "free"
    },
    { "expr": "san_storage_info", "legendFormat": "hdd1" }
   ]
  },
  {
   "title": "FAS8300-HDD-2 (CINDER_BRONZE_02)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "san_pool_total_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_BRONZE_02\"}",
     "legendFormat": "total"
    },
    {
     "expr": "san_pool_used_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_BRONZE_02\"}",
     "legendFormat": "used"
    },
    {
     "expr": "san_pool_free_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_BRONZE_02\"}",
     "legendFormat": "free"
    },
    { "expr": "san_storage_info", "legendFormat": "hdd2" }
   ]
  },
  {
   "title": "GLANCE-IMAGES",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "san_pool_total_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"glance_images\"}",
     "legendFormat": "total"
    },
    {
     "expr": "san_pool_used_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"glance_images\"}",
     "legendFormat": "used"
    },
    {
     "expr": "san_pool_free_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"glance_images\"}",
     "legendFormat": "free"
    },
    { "expr": "san_storage_info", "legendFormat": "glance" }
   ]
  },
  {
   "title": "CINDER_GOLD_01 capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_total_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_GOLD_01\"}"
    }
   ]
  },
  {
   "title": "CINDER_GOLD_02 capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_total_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_GOLD_02\"}"
    }
   ]
  },
  {
   "title": "CINDER_BRONZE_01 capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_total_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_BRONZE_01\"}"
    }
   ]
  },
  {
   "title": "CINDER_BRONZE_02 capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 17 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_total_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_BRONZE_02\"}"
    }
   ]
  },
  {
   "title": "Glance_images capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 17 },
   "repeat": "pool",
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_total_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"glance_images\"}"
    }
   ]
  },
  {
   "title": "CINDER_GOLD_01 used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_used_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_GOLD_01\"}"
    }
   ]
  },
  {
   "title": "CINDER_GOLD_02 used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 20 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_used_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_GOLD_02\"}"
    }
   ]
  },
  {
   "title": "CINDER_BRONZE_01 used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 20 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_used_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_BRONZE_01\"}"
    }
   ]
  },
  {
   "title": "CINDER_BRONZE_02 used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 20 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_used_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_BRONZE_02\"}"
    }
   ]
  },
  {
   "title": "Glance_images used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 20 },
   "repeat": "pool",
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_used_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"glance_images\"}"
    }
   ]
  },
  {
   "title": "CINDER_GOLD_01 free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_free_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_GOLD_01\"}"
    }
   ]
  },
  {
   "title": "CINDER_GOLD_02 free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 23 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_free_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_GOLD_02\"}"
    }
   ]
  },
  {
   "title": "CINDER_BRONZE_01 free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 23 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_free_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_BRONZE_01\"}"
    }
   ]
  },
  {
   "title": "CINDER_BRONZE_02 free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 23 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_free_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"vol_OPS_CINDER_BRONZE_02\"}"
    }
   ]
  },
  {
   "title": "Glance_images free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 23 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "san_pool_free_capacity_mib{backend_name=\"netapp\",instance=\"172.16.243.17:8888\",job=\"pv-san-fas8300\",san_ip=\"172.16.242.34\",volume_name=\"glance_images\"}"
    }
   ]
  },
  { "title": "Volumes statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "IO's per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "san_pool_number_read_io{backend_name=\"$backend\"}",
     "legendFormat": "Read IO - {{pool_name}}"
    },
    {
     "expr": "san_pool_number_write_io{backend_name=\"$backend\"}",
     "legendFormat": "Write IO - {{pool_name}}"
    },
    {
     "expr": "san_pool_number_read_io{backend_name=\"$backend\"} + san_pool_number_write_io{backend_name=\"$backend\"}",
     "legendFormat": "Total IO - {{pool_name}}"
    }
   ]
  },
  {
   "title": "Throughput  per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "KiBs" }
   ],
   "targets": [
    {
     "expr": "san_pool_number_read_byte_rate{backend_name=\"$backend\"}",
     "legendFormat": "Read - {{pool_name}}"
    },
    {
     "expr": "san_pool_number_write_byte_rate{backend_name=\"$backend\"}",
     "legendFormat": "Write - {{pool_name}}"
    },
    {
     "expr": "san_pool_number_read_byte_rate{backend_name=\"$backend\"} + san_pool_number_write_byte_rate{backend_name=\"$backend\"}",
     "legendFormat": "Total - {{pool_name}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "san_pool_number_read_latency{backend_name=\"$backend\"}",
     "legendFormat": "Read - {{pool_name}}"
    },
    {
     "expr": "san_pool_number_write_latency{backend_name=\"$backend\"}",
     "legendFormat": "Write - {{pool_name}}"
    },
    {
     "expr": "san_pool_number_read_latency{backend_name=\"$backend\"} + san_pool_number_write_byte_rate{backend_name=\"$backend\"}",
     "legendFormat": "Total - {{pool_name}}"
    }
   ]
  },
  { "title": "Port", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } }
 ]
}