###############################
# Driver type supported: dummy
###############################

# Port run exporter
port: 8888

# Host run in exporter
host: 0.0.0.0

# Enable debug logging for exporter
debug: false

# San-exporter will send request to SAN storage interval
# to get information and cache to file
# This config can be set in global for apply to all backend
# or can be set for specific backend
# You should set this value for each backend is not less than the driver's value recommendation.
# Unit: second
# Default: interval = 5m
interval: 300

# Timeout to mask data in cache file is old
# Calculated from the last time data in the cache file was updated to the current.
# This config can be set in global for apply to all backend
# or can be set for specific back-end
# You should set this value for each backend is not less than the driver's value recommendation.
# Unit: second
# Default: timeout = 10m
timeout: 600

# Default: /var/log/san_exporter.log
log_file: "san_exporter.log"


enabled_backends:
- 3par_8440

backends:
- name: "3par_8440"
  hpe3par_api_url: "http://127.0.0.1:5001/api/v1"
  hpe3par_username: "hpe3par_admin"
  hpe3par_password: "hpe3par_password"
  san_ssh_ip: "127.0.0.1:5001"
  san_ssh_user: "hpe3par_admin"
  san_ssh_pass: "hpe3par_password"
  san_ssh_port: 22
  timeout: 600
  interval: 300 # should not less than 5m, see the driver config below
  driver: "hpe3par"
  pools: UnitTestCPG, UnitTestCPG2
  optional_metrics:
    port: False
    cpu: False
    cpg: True
    alert: True # Note: this alert metrics will be collected via SSH